TrajectoryPlannerROS:
  # 許容される最大前進速度
  max_vel_x: 0.2
  # 許容される最小前進速度
  min_vel_x: 0.1
  # 許容される最大回転速度
  max_vel_theta: 0.2
  # rad/sでインプレース回転を実行している間, 許容される最小回転速度
  min_in_place_vel_theta: 0.1
  # ロボットのx加速制限
  acc_lim_x: 1.0
  # ロボットのy加速制限
  acc_lim_y: 1.0
  # ロボットの回転加速限界
  acc_lim_theta: 0.5
  # 速度コマンドがホロノミックまたは非ホロノミックロボットに対して生成されるかどうかを決定
  # ホロノミックロボットの場合, 移動速度コマンドをベースに発行
  # 非ホロノミックロボットの場合, 移動速度コマンドは発行されません
  holonomic_robot: true