# 局所経路計画に対するファイル
# ローカル計画と障害物回避に使用
local_costmap:
  # 地図フレームの設定
  # map：ロボットが位置するワールド座標
  global_frame: map
  # ロボットベースフレームの設定
  # base_link：オドメトリodomでのロボット位置
  robot_base_frame: base_link
  # 更新周期
  update_frequency: 5.0
  # パブリッシュ周期
  publish_frequency: 5.0
  # 与えられた地図を使用するかに関する設定
  static_map: false
  # 局所地図のwindowの設定
  rolling_window: true
  # 局所地図のwindowの横幅
  width: 4.0
  # 局所地図のwindowの縦幅
  height: 4.0
  # 局所地図のwindowの解像度
  resolution: 0.1